#!/bin/bash

cd /opt/codedeploy-agent/deployment-root/*/d-*/deployment-archive

source "$HOME/.gvm/bin/gvm-init.sh"


./grailsw clean 
./grailsw compile
./grailsw war

cp /opt/codedeploy-agent/deployment-root/*/d-*/deployment-archive/target/blagger-0.1.war /tmp/vaider.war

