#!/bin/bash

cd /opt/codedeploy-agent/deployment-root/b3479486-38c9-474a-82fd-6f03550f399d/d-*/deployment-archive

touch kmttest

source "$HOME/.gvm/bin/gvm-init.sh"

grails clean && grails compile && grails war