#!/bin/bash

cd /opt/codedeploy-agent/deployment-root/b3479486-38c9-474a-82fd-6f03550f399d/d-*/deployment-archive

source "$HOME/.gvm/bin/gvm-init.sh"

mkdir /opt/codedeploy-agent/deployment-root/b3479486-38c9-474a-82fd-6f03550f399d/d-*/deployment-archive/grails-app/migrations

./grailsw clean 
./grailsw compile
./grailsw war

cp /opt/codedeploy-agent/deployment-root/b3479486-38c9-474a-82fd-6f03550f399d/d-*/deployment-archive/target/blagger-0.1.war /tmp/vaider.war

